name: plc-remedy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - Flask==3.0.0
    - Flask-SocketIO==5.3.6
    - eventlet==0.33.3
    - pycomm3==1.2.10
    - pyyaml==6.0.1
    - requests==2.31.0
    - python-dotenv==1.0.0
    - cpppo>=4.0.0
    - gunicorn==21.2.0
    - pytest==7.4.3
    - pytest-flask==1.3.0
